### ISSUE TITLE
`shortLivedTokensExpiry` must be set up

### ISSUE THREAD

**Issue by heurtematte** [gradle/develocity-gitlab-templates#59]
Default value for shortLivedTokensExpiry is an empty string, that raises this issue in gitlab CI: Instance type (string) does not match any allowed primitive type (allowed: [\"integer\",\"number\"]

Develocity version: 2024.1.6

* https://github.com/gradle/develocity-gitlab-templates/blob/45c1186428f2f28f3917bf1a05e87b0a7b8678d6/src/gradle/develocity-gradle.template.yml#L12
*https://github.com/gradle/develocity-gitlab-templates/blob/45c1186428f2f28f3917bf1a05e87b0a7b8678d6/develocity-maven.yml#L11

1. `shortLivedTokensExpiry` not specify: token is passed to expiresInHours

```shell
curl -s -w '\n%{http_code}' -X POST 'https://develocity-staging.eclipse.org/api/auth/token?expiresInHours=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' -H 'Authorization: Bearer '
local 'response={"title":"Request validation failed.","type":"urn:gradle:develocity:api:problems:validation","status":400,"detail":"Instance type (string) does not match any allowed primitive type (allowed: [\"integer\",\"number\"]) (Additional info: Query parameter: expiresInHours)"}
```

2. shortLivedTokensExpiry specify with `1h` as a string: don't understand `1h`

```shell
curl -s -w '\n%{http_code}' -X POST 'https://develocity-staging.eclipse.org/api/auth/token?expiresInHours=1h' -H 'Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXX'
local 'response={"title":"Request validation failed.","type":"urn:gradle:develocity:api:problems:validation","status":400,"detail":"Instance type (string) does not match any allowed primitive type (allowed: [\"integer\",\"number\"]) (Additional info: Query parameter: expiresInHours)"}
```

3. shortLivedTokensExpiry with an integer: input: provided value is not a string

```yaml
  - remote: 'https://raw.githubusercontent.com/gradle/develocity-gitlab-templates/1.3.0/develocity-maven.yml'
    inputs:
      url: https://develocity-staging.eclipse.org
      shortLivedTokensExpiry: 2
```

=> `https://raw.githubusercontent.com/gradle/develocity-gitlab-templates/main/develocity-gradle.yml`: `shortLivedTokensExpiry` input: provided value is not a string

4. This configuration works: 

```yaml
  - remote: 'https://raw.githubusercontent.com/gradle/develocity-gitlab-templates/1.3.0/develocity-maven.yml'
    inputs:
      url: https://develocity-staging.eclipse.org
      shortLivedTokensExpiry: '2'
```

```shell     
curl -s -w '\n%{http_code}' -X POST 'https://develocity-staging.eclipse.org/api/auth/token?expiresInHours=2' -H 'Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXX'
local 'response={"title":"Request validation failed.","type":"urn:gradle:develocity:api:problems:validation","status":400,"detail":"Instance type (string) does not match any allowed primitive type (allowed: [\"integer\",\"number\"]) (Additional info: Query parameter: expiresInHours)"}
```
